/* Big Header */

#pragma once
#ifndef TEMPLATE_42_REPO_H
# define TEMPLATE_42_REPO_H

# include "initializer.h"

#define CONTENT_MAIN_C "/* ************************************************************************** */\n\
						/*                                                                            */\n\
						/*                                                        :::      ::::::::   */\n\
						/*   main.c                                             :+:      :+:    :+:   */\n\
						/*                                                    +:+ +:+         +:+     */\n\
						/*   By:                                            +#+  +:+       +#+        */\n\
						/*                                                +#+#+#+#+#+   +#+           */\n\
						/*   Created:                     by initializer       #+#    #+#             */\n\
						/*                                                    ###   ########.fr       */\n\
						/*                                                                            */\n\
						/* ************************************************************************** */\n\
						\n\
						#include <stdio.h>\n\
						\n\
						int main(int argc, char **argv)\n\
						{\n\
							printf(\"Hello, World!\\n\");\n\
							return (0);\n\
						}"

# define CONTENT_MAIN_H "/* ************************************************************************** */\n\
						/*                                                                            */\n\
						/*                                                        :::      ::::::::   */\n\
						/*   main.h                                             :+:      :+:    :+:   */\n\
						/*                                                    +:+ +:+         +:+     */\n\
						/*   By:                                            +#+  +:+       +#+        */\n\
						/*                                                +#+#+#+#+#+   +#+           */\n\
						/*   Created:                     by initializer       #+#    #+#             */\n\
						/*                                                    ###   ########.fr       */\n\
						/*                                                                            */\n\
						/* ************************************************************************** */\n\
						\n\
						#ifndef MAIN_H\n\
						# define MAIN_H\n\
						\n\
						/* -----| Header |----- */\n\
						// Global (<stdio.h>, ...)\n\
						//...\n\
						\n\
						// Local (\"main.h\", ...)\n\
						//...\n\
						\n\
						/* -----| Define |----- */\n\
						// Your #define like #define MAX 42\n\
						\n\
						/* -----| Enum |----- */\n\
						// Your enum like enum e_my_enum { A, B, C };\n\
						\n\
						/* -----| Union |----- */\n\
						// Your union like union u_my_union { int a; char *b; };\n\
						\n\
						/* -----| Typedef |----- */\n\
						// Your typedef like typedef unsigned int t_uint;\n\
						\n\
						/* -----| Struct |----- */\n\
						// Your struct like struct s_my_struct { int a; char *b; };\n\
						\n\
						/* -----| Prototype |----- */\n\
						// Your prototype like int my_function(int a, char *b);\n\
						\n\
						#endif	// MAIN_H";

# define CONTENT_MAKEFILE	"# Big Header\n\
							\n\
							# This Makefile has been created by initializer V2. It is used to compile nor\n\
							# run you project in C of the 42 school. It is designed to be run on a Unix-like\n\
							# system. It has been tested on Ubuntu 18.04. It should work on other Unix-like\n\
							# systems as well.\n\
							\n\
							# This Makefile requires the following tools:\n\
							# - make\n\
							# - cc\n\
							\n\
							# This Makefile has the following targets:\n\
							# - all: Compiles the project.\n\
							# - compile: Compiles the file but not the executable (useless alone).\n\
							# - clean: Removes all files generated by this Makefile.\n\
							# - fclean: Removes all files generated by this Makefile and the executable.\n\
							# - re: Removes all files generated by this Makefile and compiles the project.\n\
							\n\
							# This Makefile has the following variables:\n\
							# - NAME: The name of the executable.\n\
							# - CC: The compiler to use.\n\
							# - CFLAGS: The flags to use with the compiler.\n\
							# - DEBUG: The flags to use with the compiler for debugging.\n\
							\n\
							# This Makefile has the following directories:\n\
							# - DIR_SRC: The directory where the source files are.\n\
							# - DIR_OBJ: The directory where the object files are.\n\
							# - DIR_INC: The directory where the include files are.\n\
							\n\
							\n\
							NAME =	a.out\n\
							\n\
							CC =		cc\n\
							CFLAGS =	-Wall -Wextra -Werror\n\
							DEBUG =		-g3\n\
							\n\
							DIR_SRC =	src\n\
							DIR_OBJ =	.obj\n\
							DIR_INC =	include\n\
							\n\
							SRC =	main.c\n\
							\n\
							OBJ = $(SRC:%.c=$(DIR_OBJ)/%.o)\n\
							\n\
							all: $(NAME)\n\
							\n\
							compile: $(OBJ)\n\
								@mkdir -p $(DIR_OBJ)\n\
							\n\
							$(DIR_OBJ)/%.o: $(DIR_SRC)/%.c\n\
								@mkdir -p $(@D)\n\
								$(CC) $(CFLAGS) -I$(DIR_INC) -c $< -o $@\n\
							\n\
							$(NAME): compile\n\
							\n\
							clean:\n\
								rm -rf $(DIR_OBJ)\n\
							\n\
							fclean: clean\n\
								rm -f $(NAME)\n\
							\n\
							re: fclean all\n\
							\n\
							.PHONY: all compile clean fclean re";

#define CONTENT_GITIGNORE	"*.o\n\
							*.out\n\
							.vscode\n\
							.test\n\
							.obj\n\
							*.dSYM\n\
							*.DS_Store\n\
							*.swp";

extern const t_template tmp_42_repo;

#endif	// TEMPLATE_42_REPO_H